before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: bWbpxD+l8zVdWK2NJuKi/w4aSMK7BqxNcAnFFLR5JReJxWGJIUSBg2dGIGy6aT1UzGOXOep50uPHb3zgmwuTv61Ym2yWfrmgsLIw5zN5TydGJKj+SNI5Uwrr3XpGEl3ua2DzN/NIFPOaCGic94RrA7XMJKgE4V/Vp+wb6zXCMPNAPfGvIYoWfs1iljy05yUdpNBwoY8FEksyU7h+tw95HWqzOZNETVWn7B7gsm0EvrC4ZAT27b92y+aHutqWcZt7v4nY0hgxeaMHEyED32VnglwDEymqjfOAXygKnBM4ZBxo4G4MNwZb7Lf8uM8ZR7wVt9fIShDlDWNonnTmzW4mpPv/Xogh+3HcFfdo47u9RwNT/s6I8tPHdV42HsP/1mYFJBzT41v8aQJJy9uXMLo9dk+B2xeMZiT5awPpHoD6ZU3LpDYTpHPDvx4k+HsfQVuvmJQdaLvREDFD5n8VUqJR8Cx2ecoYRK91uu3xjYRgxXRDbothyW05lVBbNLJqv8SVuC1Jh/5jQLlgsaJyeRFrj8AuOfM2CoHAkn9zUaK7IsEiM4F+Ih4Gxv5U7SFQ1EXPxMBsLE7tisFtd2mm+3dq7tJM4NJubNyN4HBF+FTxJ2B4V7stBBpUZvKQ6oVCL2oBPQ2kzk/qUf8NtyfMVWecYCyWsAB08l69J+uwr8Gl8xA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
